#!/bin/bash
# vim: ft=sh

setxkbmap -layout $((\
        echo 'us';\
        echo 'us,ru';\
        echo 'us,us,ru -variant ,colemak,';\
        ls /usr/share/X11/xkb/symbols | grep '^..$';\
    ) | rofi -dmenu -p layout)
xmodmap -e "$(xmodmap -pke | grep 108 | sed 's/ISO_Level3_Shift/ISO_Next_Group/g')"
pkill -RTMIN+10 i3blocks
