#!/bin/bash
name="$(~/.i3/vinput)"
[ $? -eq 0 ] || exit $?
num="$(~/.i3/cur-wksp)"
if [ -z "$name" ]
then
    i3-msg "rename workspace to $num"
else
    i3-msg 'rename workspace to "'"$num:$name"'"'
fi
