#!/bin/bash

status="$(mpc | sed -n 2p)"
if [ -n "$status" ]
then
    color=$(grep playing <<<"$status" >/dev/null && echo white || echo grey)
    mpc -f '%title%' | sed '
    1{
      s/^\(.\{20\}\).*/\1/;
      s/.*/<span weight="bold" color="'$color'">&<\/span>/;
    }
    2{
      s/^\[[a-z]*\] *#[0-9]*\/[0-9]* *//;
    }
    3{
      s/volume://;
      s/repeat: on/r/; s/random: on/z/; s/single: on/s/; s/consume: on/c/;
      s/[a-z]*: off//g;
      s/ //g; s/%/% /; s/ $//;
      s/.*/<span color="grey">&<\/span>/;
    }
    ' | tr $'\n' ' ' | sed 's/ $//'
else
    echo '<span color="grey">no music playing</span>'
fi
