#!/usr/bin/env bash

case $BLOCK_BUTTON in
    3) mpc random >/dev/null ;;
    4) mpc volume +5 >/dev/null ;;
    5) mpc volume -5 >/dev/null ;;
esac

exec 4< <(mpc -f '%title%')
read line1 <&4
read line2 <&4
read line3 <&4
exec 4<&-

shopt -s extglob

if [ -n "$line2" ]
then
    color=$(grep playing <<<"$line2" >/dev/null && echo white || echo grey)
    echo -n "<span weight='bold' color='$color'>"
    if [ ${#line1} -gt 20 ]
    then
        offset=$[3*$(date +%s) % (${#line1} + 3)]
        line1="$line1   $line1"
        echo -n "${line1:$offset:20}"
    else
        echo -n "${line1:0:20}"
    fi
    echo -n '</span>'
    echo -n " ${line2##\[*\]*( )\#+([0-9])/+([0-9])*( )} "
    sed '
      s/volume://;
      s/repeat: on/r/; s/random: on/z/; s/single: on/s/; s/consume: on/c/;
      s/[a-z]*: off//g;
      s/ //g; s/%/% /; s/ $//;
      s/.*/<span color="grey">&<\/span>/;
    ' <<<"$line3"
else
    echo '<span color="grey">no music playing</span>'
fi
