#!/usr/bin/env bash

case $BLOCK_BUTTON in
  3) wpctl set-mute "$BLOCK_INSTANCE" toggle ;;
  4) wpctl set-volume "$BLOCK_INSTANCE" 5%+ ;;
  5) wpctl set-volume "$BLOCK_INSTANCE" 5%- ;;
esac

vol="$(wpctl get-volume "$BLOCK_INSTANCE")"
num="$(cut -c 9-12 <<<"$vol" | sed 's/\.//; s/^00\?//')%"
grep MUTED <<<"$vol" >/dev/null && echo "<span color='#644'>$num</span>" || echo "$num"
