#! /nix/store/cinw572b38aln37glr0zb8lxwrgaffl4-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/gli79g4rcbhylhsjv22ljpqi580rpsyb-alsa-utils-1.1.8/bin'${PATH:+':'}$PATH
exec -a "$0" "/nix/store/0f83w4np6bac5hwrlp62cmd741vx2kxw-i3blocks-1.4/libexec/i3blocks/.volume-wrapped"  "${extraFlagsArray[@]}" "$@"
